[klibc] s390: mmap: Change inline assembly to work with Clang
Clang rejects the operand "%b1" to svc:

    usr/klibc/arch/s390/mmap.c:61:3: error: invalid operand in inline asm: '    svc ${1:b}'

Since svc always takes an immediate operand, the "b" modifier is not
needed.  After deleting it, both Clang and gcc generate the correct
instruction "svc 90".

Signed-off-by: Ben Hutchings <ben@decadent.org.uk>